env_vars = ["VAR1"]

# This code is executed on every Vagrant command, therefore, we don't check
# anything and don't echo any messages here. All necessary checks should be
# done in the provision script
env_vars_with_values = Hash.new
env_vars.each do |env_var|
  env_vars_with_values[env_var] = ENV[env_var]
end

Vagrant.configure("2") do |config|
  # config.vm.box = "ubuntu/xenial64"
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    #vb.memory = "2048"
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    # prevent 'ubuntu-xenial-16.04-cloudimg-console.log' file creation
    # https://groups.google.com/forum/#!topic/vagrant-up/eZljy-bddoI
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    vb.customize ["sharedfolder", "add", :id, "--name", "debug", "--hostpath",
      File.expand_path("../../../../..", File.dirname(__FILE__)), "--automount"]
  end
  config.vm.network "private_network", virtualbox__intnet: "vagrant-ddclient", ip: "172.24.0.11"
  config.vm.hostname = "ubuntu"

  # config.vm.provision "shell", path: "../../provision/client.sh", keep_color: true

  config.vm.provision "shell", path: "../../provision/env_vars.sh", keep_color: true,
    env: env_vars_with_values, args: [env_vars.join(" "), "second"], privileged: false
end
