Vagrant.configure("2") do |config|
  # config.vm.box = "ubuntu/xenial64"
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    #vb.memory = "2048"
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    # prevent 'ubuntu-xenial-16.04-cloudimg-console.log' file creation
    # https://groups.google.com/forum/#!topic/vagrant-up/eZljy-bddoI
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    vb.customize ["sharedfolder", "add", :id, "--name", "provision", "--hostpath", File.expand_path("../../provision", File.dirname(__FILE__)), "--automount"]
  end
  config.vm.network "private_network", virtualbox__intnet: "vagrant-ddclient", type: "dhcp"

  config.vm.provision "shell", inline: "/media/sf_provision/client.sh", keep_color: true
end
