Vagrant.configure("2") do |config|
  # config.vm.box = "opensuse/openSUSE-Tumbleweed-x86_64"
  config.vm.box = "archlinux/archlinux"
  config.vm.provider "virtualbox" do |vb|
    #vb.memory = "2048"
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    # vb.customize ["sharedfolder", "add", :id, "--name", "provision", "--hostpath", File.expand_path("../../provision", File.dirname(__FILE__)), "--automount"]
  end
  # config.vm.network "private_network", virtualbox__intnet: "vagrant-ddclient", type: "dhcp"
  config.vm.network "private_network", virtualbox__intnet: "vagrant-ddclient", ip: "172.24.0.14"

  config.vm.provision "shell", path: "../../provision/client.sh", keep_color: true
end
