env_vars = ["DDCLIENT_TEST_AWS_ACCESS_KEY", "DDCLIENT_TEST_AWS_SECRET_KEY",
  "DDCLIENT_TEST_AWS_REGION"]

# This code is executed on every Vagrant command, therefore, we don't check
# anything and don't echo any messages here. All necessary checks should be
# done in the provision script
env_vars_with_values = Hash.new
env_vars.each do |env_var|
  env_vars_with_values[env_var] = ENV[env_var]
end

Vagrant.configure("2") do |config|
  # config.vm.box = "ubuntu/xenial64"
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    #vb.memory = "2048"
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    # prevent 'ubuntu-xenial-16.04-cloudimg-console.log' file creation
    # https://groups.google.com/forum/#!topic/vagrant-up/eZljy-bddoI
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    vb.customize ["sharedfolder", "add", :id, "--name", "multi-ip-ddclient", "--hostpath",
      File.expand_path("../../../", File.dirname(__FILE__)), "--automount"]
  end
  config.vm.hostname = "aws-cli"

  config.vm.provision "shell", name: "Vagrant guest configuration",
    path: "../../scripts/vagrant_vm.sh", keep_color: true

  config.vm.provision "shell", name: "Python 3 installation",
    path: "../../scripts/python.sh", keep_color: true

  config.vm.provision "shell", name: "AWS CLI installation",
    inline: "pip3 install awscli boto3", keep_color: true

  config.vm.provision "shell", name: "Environment variables",
    path: "../../scripts/vagrant_env_vars.sh", keep_color: true,
    env: env_vars_with_values, args: [env_vars.join(" ")], privileged: false

  config.vm.provision "shell", name: "AWS CLI configuration",
    keep_color: true, privileged: false,
    inline: <<-SHELL
      aws configure set aws_access_key_id ${DDCLIENT_TEST_AWS_ACCESS_KEY}
      aws configure set aws_secret_access_key ${DDCLIENT_TEST_AWS_SECRET_KEY}
      aws configure set default.region ${DDCLIENT_TEST_AWS_REGION}
    SHELL

end