env_vars = ["DDCLIENT_TEST_AWS_ACCESS_KEY", "DDCLIENT_TEST_AWS_SECRET_KEY",
  "DDCLIENT_TEST_AWS_REGION"]

# This code is executed on every Vagrant command, therefore, we don't check
# anything and don't echo any messages here. All necessary checks should be
# done in the provision script
env_vars_with_values = Hash.new
env_vars.each do |env_var|
  env_vars_with_values[env_var] = ENV[env_var]
end

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    #vb.memory = "2048"
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    # prevent 'ubuntu-xenial-16.04-cloudimg-console.log' file creation
    # https://groups.google.com/forum/#!topic/vagrant-up/eZljy-bddoI
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]

    config.vm.synced_folder "../../saltstack/", "/srv/salt"
    config.vm.synced_folder "../../../", "/multi-ip-ddclient"
  end
  config.vm.hostname = "aws-cli"

  config.vm.provision :salt do |salt|
    salt.minion_config = "./saltstack_minion"
    salt.masterless = true
    salt.run_highstate = true
    salt.install_type = "stable"
    # salt.verbose = true
  end

  config.vm.provision "shell", name: "Environment variables",
    path: "../../scripts/vagrant_env_vars.sh", keep_color: true,
    env: env_vars_with_values, args: [env_vars.join(" ")], privileged: false

  config.vm.provision "shell", name: "AWS CLI configuration",
    keep_color: true, privileged: false,
    inline: <<-SHELL
      aws configure set aws_access_key_id ${DDCLIENT_TEST_AWS_ACCESS_KEY}
      aws configure set aws_secret_access_key ${DDCLIENT_TEST_AWS_SECRET_KEY}
      aws configure set default.region ${DDCLIENT_TEST_AWS_REGION}
    SHELL
end