Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    vb.memory = "1024"
  end
  config.vm.synced_folder "../../saltstack/", "/srv/salt"
  config.vm.synced_folder "../../../", "/multi-ip-ddclient"

  config.vm.define :"ubuntu-xenial", autostart: false do |ubuntu_xenial|
    ubuntu_xenial.vm.box = "ubuntu/xenial64"
    ubuntu_xenial.vm.hostname = "client-ubuntu-xenial"
    ubuntu_xenial.vm.provider "virtualbox" do |vb|
      # prevent 'ubuntu-xenial-16.04-cloudimg-console.log' file creation
      # https://groups.google.com/forum/#!topic/vagrant-up/eZljy-bddoI
      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end
  end

  config.vm.define :"centos-6", autostart: false do |centos_6|
    centos_6.vm.box = "centos/6"
    centos_6.vbguest.auto_update = true
    centos_6.vm.hostname = "client-centos-6"
  end

  config.vm.provision :salt do |salt|
    # [!!!!!] Change after debug
    salt.minion_config = "../aws-cli/saltstack_minion"
    salt.masterless = true
    salt.run_highstate = true
    salt.install_type = "stable"
    # salt.verbose = true
  end
end