Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |vb|
    #vb.memory = "2048"
    vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    # vb.customize ["sharedfolder", "add", :id, "--name", "provision", "--hostpath", File.expand_path("../../provision", File.dirname(__FILE__)), "--automount"]
  end
  config.vm.network "private_network", virtualbox__intnet: "vagrant-ddclient", ip: "172.24.0.12"

  # config.vm.provision "shell", inline: "/media/sf_provision/client.sh", keep_color: true
  config.vm.provision "shell", path: "../../provision/client.sh", keep_color: true
end
